export const Images = {
  linkArrow: require("./images/arrow.png"),
  linkArrowDefault: require("./images/arrow-default.png"),
  folderImage: require("./images/folder.png"),
  testImage1: require("./images/test-1.png"),
  testImage2: require("./images/test-2.png"),
  passTestImage: require("./images/pass-test.png"),
  repoImage: require("./images/repo.png"),
  repoMobileImage: require("./images/repo-mobile.png"),
  actionsImage: require("./images/github-actions.png"),
  actionsMobileImage: require("./images/github-actions-mobile.png"),
  workflowsImage: require("./images/workflows.png"),
  triggerImage: require("./images/trigger.png"),
  logsImage: require("./images/logs.png"),
};
